[package]
name = "gear"
version = "0.1.0"
edition = "2018"

[[test]]
name = "test"
path = "src/tests.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
