[package]
name = "gear"
version = "0.1.0"
edition = "2018"
license = "BSD-3-Clause"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "./lib.rs"

[dependencies]
lazy_static = "1.4.0"
component_macro = { path = "../component_macro" }